--------------------------------------------------------
--  File created - Thursday-January-17-2019   
--------------------------------------------------------
begin
  execute immediate 'truncate table PC_OBFUSCATN_RULES';
end;
/

REM INSERTING into PC_OBFUSCATN_RULES
SET DEFINE OFF;
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Birth Date','DATE30_DAYS','ut.RD30',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Telephone','OBFUS_TEL','ut.OFT',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder','HOLDER','ut.TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Name','HOLDER_NAME','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Address','SHUFFLE_COUNTRY','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Address Sync','INHERIT_HA','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Bank Address Sync','INHERIT_BA','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Web','OBFUS_WEB','ut.OFW',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Address','SUBS_DIGITS_TRANSFORM_CHAR','ut.TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Name Sync','INHERIT_HN','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Financial','SUBS_DIGITS_TRANSFORM_CHAR','ut.TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Comp Contact','SUBS_DIGITS_TRANSFORM_CHAR','ut.TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Date Sync','INHERIT_HO','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Beneficial Holder Name','SUBS_DIGITS_TRANSFORM_CHAR','ut.TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII CREST','SUBS_DIGITS_TRANSFORM_CHAR','ut.TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Comp Sensitive','SUBS_DIGITS_TRANSFORM_CHAR','ut.TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Sync','INHERIT_HO','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Obscure','SUBS_DIGITS_TRANSFORM_CHAR','ut.TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Email','OBFUS_EMAIL','ut.OFE',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Date','DATE30_DAYS','ut.RD30',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Cheque Number','CHEQUE_SHUFFLE','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Country Partition','COUNTRY_PARTITION','ut.EXCLUDE',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Sort Code Key','GEN_SORT_KEY','ut.EXCLUDE',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Configuration','NONE','ut.EXCLUDE',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Obscure Text','OBSFUS_TEXT','ut.RN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Designation','DESIGNATION','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Bank Account','OBFUS_BANK_ACCOUNT','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Bank Address','SHUFFLE_BANK_ADDRESS','ut.MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Bank Account Sync','INHERIT_BA','ut.MAN',null);
commit;