--------------------------------------------------------
--  File created - Monday-March-4-2019   
--------------------------------------------------------
begin
  execute immediate 'truncate table PSEUDO_CONS_COLUMNS';
end;
/

REM INSERTING into PSEUDO_CONS_COLUMNS
SET DEFINE OFF;
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','REV_TOTAL_ID');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','BANK_SORT_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','ACCOUNT_NO');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','CURRENCY_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','REVERSED_TRANSACTION_COUNT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','TRANSACTION_SUSPENSE_COUNT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','ALREADY_REVERSED_COUNT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','TRANSACTION_ERROR_COUNT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','REVERSED_TRANSACTION_AMOUNT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','TRANSACTION_SUSPENSE_AMOUNT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','ALREADY_REVERSED_AMOUNT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','TRANSACTION_ERROR_AMOUNT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','CREATED_BY');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','CREATED_DATE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','MODIFIED_BY');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_BANK_REVERSAL_TOTALS','MOD_TIMESTAMP');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','REV_TOTAL_ID');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','BANK_SORT_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','ACCOUNT_NO');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','CASH_TRANSACTION_ID');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','IVC_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','REGISTRATION_DATE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','TRANSACTION_AMOUNT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','REVERSAL_MSG_TYPE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','ERROR_DESCRIPTION');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','ACCOUNT_FORENAME');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','ACCOUNT_SURNAME');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','CREATED_BY');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','CREATED_DATE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','MODIFIED_BY');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','MOD_TIMESTAMP');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('IMPORT','RR556_CNB_REVERSAL_REPORT','ERROR_ID');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','PROCESSID');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','COMP_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','COMP_NAME');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','EVENT_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','RECORD_DATE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','CAG_EVENT_TYPE_SUB_TYPE_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','PAYMENT_NO');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','CLASS_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','PAY_DATE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','RATE_PER_SHARE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','HOLDER_IVC_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','HOLDER_NAME');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','HOLDER_CODE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','DATE_LEFT');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','HOLDING_ELIGIBLE_DRIP');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','HOLDING_ELIGIBLE_CASH');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','INELIGIBLE_HOLDING');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','FORFEITS_DUE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','DIVIDEND_DUE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','ELECT_FOR_DRIP');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','CASH_BROUGHT_FWD');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','TOTAL_CASH_AVAILABLE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','AVAILABLE_FOR_DRIP');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','EXCESS_CASH');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','TAX_RATE');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','SECONDARY_TAX');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','HOLDING');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','SIP_RECORD_DATE_HOLDINGS');
Insert into PSEUDO_CONS_COLUMNS (OWNER,TABLE_NAME,COLUMN_NAME) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING','SIP_FORFEITED_SIP_SHARES');

commit;
 