

set define off;
delete from  ss_load_excl_config;

-- Exclsions based on size for  company partition tables
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RPTINSTANCES');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','OUTPUTFILES');
insert into ss_load_excl_config(owner,table_name) values ('IMPORT','IMPORT_STAGING_TABLE');
insert into ss_load_excl_config(owner,table_name) values ('INTEGRATION','JOB_DATA');
insert into ss_load_excl_config(owner,table_name) values ('LOG','ERROR_LOGS');
insert into ss_load_excl_config(owner,table_name) values ('LOG','LOGS');


-- Exclsions based on size for non company partition tables
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FLOW_TEST');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','FR872_GEN_SIP_PLAN_DISPOSALS');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR580_EVT_PAYMENT_STG');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','DRIP_HOLDER_LOAD_STAGING');
insert into ss_load_excl_config(owner,table_name) values ('CORRESPONDENCE','CORRES_PARAM_COLL_ITEMS');
insert into ss_load_excl_config(owner,table_name) values ('IMPORT','RR570_IMP_REC_REP_SUMMARIES');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','MULTIPLE_REPORTS_STAGE');
insert into ss_load_excl_config(owner,table_name) values ('CORRESPONDENCE','CORRES_PARAM_COLL_HEADER');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR554_BANK_TRAN_BY_DATE_ERRORS');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','SIP_RPT_STAGED_DATA_MAPPINGS');

-- Exclsuions of temporary (_TMP,_TEMP) tables

insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','EVENT_DATA_SUMMARY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR478_APPA_REINV_REP_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','IVC_MARKER_ELECTION_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','IVC_OUTTURNS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','HOLDER_CLASS_COPY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','SIP_HOLDERS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','CASH_CALC_SUMMARY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','TAX_REGISTER_ELECTIONS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','WAIVER_CLASS_COPY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','CASH_DIVIDEND_TRANSACTION_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','REINVEST_ELECTION_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_PARAMS','RR520_CASH_CALC_RECORD_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','COMPANIES_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','FR589_SUPPRESSED_IVCS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HLDR_NAMES_OUTRNS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_FLAGS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','CTV_DETAILS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','CALC_PAYMENTS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','FR589_PAYMENT_DTLS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR040_OPTION_PROGRESS2_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR699_MONEY_LAUNDERING_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','FR564_PTCP_SHAREAWD_RSLTS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR381_COMMON_COLS_1_2_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR568_IVC_OUTTURNS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','FR591_MARKER_DATA_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','FR591_ELIGIBLE_HOLDERS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR391_OUTSTANDING_LEAVR_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','REGISTERED_SHARE_HOLDER_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR405_GEN_SAP_INVOICING_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR416_SHARE_HOLDINGS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR416_SHARE_CONTRIBS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR377_SHAREPLAN_DTL_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR526_DIVIDEND_EXCP_RPT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR526_DIV_EXCP_DATA_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','HOLDER_EXTRACT_DETAILS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','HLD_CLASS_ELECTION_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','HLD_IVC_STATUS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','RR643_VESTING_SCHEDULE_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','RPTINST_IDS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','HOLDER_FILTER_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','OPTION_PROGRESS_MIS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_CASH_ACCOUNTS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR381_SIP_TRANS_DTL_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_PARAMS','RR520_EVENT_GRPS_RATES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_PARAMS','IVC_ELECTION_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_PARAMS','IVC_HOLDING_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR400_GEN_SIP_MOVEMENT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('IMPORT','FR958_INSTRUCTS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','PARTICIPANT_LIMIT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR056_APPLICATION_QUERY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR381_ISP_DETAILS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR539_ACC_GROUP_TOTALS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR478_APPA_WAIVER_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR478_APPA_TAX_DED_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR478_APPA_CASH_PAY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','SIP_CASH_RECON_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR478_APPB_FUND_SCHD_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','IVC_CLASS_COPY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','PAYMENT_SUPPRESSION_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','CA_CALCS_PERMIT_REINVEST_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','REGISTER_ELECTION_WAIVER_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','FR948_HOLDERS_COUNT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','FR846_CORRESPONDENCE_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','REINVEST_DETAILS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','CURRENCY_ELECTION_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','UPD_IVC_CLASS_COPY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','IVC_REINVEST_OUTTRUNS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','REINVEST_IVC_CLASS_COPY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','CASH_IVC_CLASS_COPY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','CALC_SCRIP_BY_RATIOS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','CALC_REINVEST_VALUES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','REINVESTMENT_SUMMARY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','IVC_CLASS_COPY_TAX_RATES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','RESIDUAL_REINVEST_ELECT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','REGISTER_ELECT_CURRENCY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','CALC_PAYMENTS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','MAINTAIN_HOLDER_CHANGES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','COMP_CODE_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','REG_ELECTION_REQ_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','FR591_CLASS_DATA_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','FR591_TAX_VOUCHER_DATA_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR416_EMP_LEAVER_HOLDING_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR377_SHAREPLAN_SMRY_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR391_LEAVER_CASH_BAL_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR353_HOLDER_BULK_DATA_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR473_REINVEST_OUTTRN_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR473_DRIP_OUTTRN_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR473_NIL_PAY_OUTTRNS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR299_FORFEITURE_ON_DATE_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','PROXY_VOTING_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_STMTS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_CONTACTS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_ADDRESSES_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','RETAIL_OUTTRN_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','VOUCHER_NAME_ADDRESS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','FR589_OVERRIDE_IVCS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','CELL_RULES_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_OUTTURN_INCL_EXCL_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','DRIP_BROKER_CONTRACT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDERS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_LABELS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','APACS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_CLASS_TAX_DTLS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','CERTIFICATE_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','REGISTER_ELECTIONS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_MARKER_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','BENEFICIAL_HOLDERS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR410_GEN_DISPOSAL_REQ_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR654_DISC_EXER_REQ_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR539_DETAIL_CASH_TRANSAC_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR011_HOLDER_DETAILS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR539_PAYMENT_DETAIL_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR410_GEN_ANTIFRUD_HVAL_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR381_HOLDERS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR381_SIP_CASH_BALANCE_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','HOLDER_ELECTION_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR381_COMMON_COLS_1_2_3_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','IVC_CLASS_TAX_RATES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR898_DPA_REMAINING_SHR_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','RR613_DISC_OPTION_PROGRES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','ERROR_INFO_SUCCESS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','AWARD_FILTER_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR899_HOLDER_MANDATES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','SHARE_MOVEMENTS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR999_HOLDER_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR2005_HOLDERS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','UNCHECKED_CHANGES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','EVENTS_FILTER_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','RR613_STATUS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_MANDATES_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_INCL_EXCL_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','CALC_REINVEST_VALUES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR381_SIP_SHARE_BALANCE_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR539_CASH_ACC_BALANCE_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_PARAMS','RR520_TAX_PAY_RATES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_PARAMS','RR520_CAG_EVENT_DATA_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_PARAMS','FR896_ELIGIBLE_HOLDERS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('CASH_MANAGEMENT','CASH_ACCOUNT_BALANCE_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('CASH_MANAGEMENT','RR58_CASH_TRANS_RECONCIL_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR694_HLD_BAL_MSL_DTLS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR614_DISC_AWARD_STATUS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR381_ISP_CURRENCIES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR040_OPTION_PROGRESS1_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR614_DISC_AWRD_SHR_REQ_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','RR613_FR906_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','REINVEST_CA_CALC_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','REG_ELECTION_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR473_PAYMENT_OUTTRNS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','CLASS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','CA_CALC_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','IVC_DRIP_OUTTRNS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','HOLDER_NAMES_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR898_DISCRET_PTCP_AWARDS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','IVC_MARKER_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','REINVEST_COPIES_HOLDER_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','IVC_PAY_OUTTRNS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('CORRESPONDENCE','HEADER_DELIVERIES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_PARAMS','IVC_ELECTION_ITEM_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR416_LOCAL_CONTRIBS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','CHEQUE_NAME_ADDRESS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR615_DISC_AWRD_RECONC_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','TAX_CLASS_DATA_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FTP_RPTINST_IDS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','FR591_OUTTURN_DATA_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR389_FILTERED_HOLDERS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR478_APPA_CAP_SUMM_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','REINVEST_SPREAD_RATES_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR603_LAPS_LAPSBLE_DPAS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR473_EVT_CALC_EXC_RPT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','RR613_DISC_OPT_PRGRSS_INS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','HOLDER_ELECTION_PRESENT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','FR589_PAYMENT_HOLDERS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR478_APPA_TAX_CRED_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR418_GEN_DIRECTOR_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR315_HOLDER_CERTS_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','EVENT_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('DATA_EXTRACT','CLASS_CALCS_841_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('REPORTING','RR654_DISC_EXCER_INSTRUCT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CAG_DATA','FR719_SYNC_CASH_ACCOUNT_TEMP');
insert into ss_load_excl_config(owner,table_name) values ('CASH_MANAGEMENT','CA_BALANCE_TMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','CREDIT_CASH_TRANSACTION_TMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR2007_AEOI_HOLDERS_TMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR2007_EXCEPTIONS_TMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','FR2007_IMPORT_STAGING_TMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','RR351_CLASS_TOTALS_TMP');
insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','RR351_REGISTER_REPORT_TMP');


--Exclude IOT Overflow tables

insert into ss_load_excl_config(owner,table_name) values ('INTEGRATION','SYS_IOT_OVER_12794374');
insert into ss_load_excl_config(owner,table_name) values ('INTEGRATION','SYS_IOT_OVER_12794191');

--Exclude Companies (this is loadfed independently)

insert into ss_load_excl_config(owner,table_name) values ('PRISM_CORE','COMPANIES');

--Exclude 'generated always identity' column
insert into ss_load_excl_config(owner,table_name) values ('CASH_MANAGEMENT','ELEC_PYMNT_FUND_RTRN_STAGING');


commit;