begin
  execute immediate 'truncate table PC_OBFUSCATN_RULES';
end;
/
truncate table PC_OBFUSCATN_RULES

REM INSERTING into PC_OBFUSCATN_RULES
SET DEFINE OFF;


REM INSERTING into PC_OBFUSCATN_RULES
SET DEFINE OFF;
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Birth Date','DATE30_DAYS','RD30',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Telephone','OBFUS_TEL','OFT',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder','HOLDER','TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Name','HOLDER_NAME','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Address','SHUFFLE_COUNTRY','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Address Sync','INHERIT_HA','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Bank Address Sync','INHERIT_BA','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Web','OBFUS_WEB','OFW',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Address','SUBS_DIGITS_TRANSFORM_CHAR','TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Name Sync','INHERIT_HN','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Financial','SUBS_DIGITS_TRANSFORM_CHAR','TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Comp Contact','SUBS_DIGITS_TRANSFORM_CHAR','TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Date Sync','INHERIT_HO','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Beneficial Holder Name','SUBS_DIGITS_TRANSFORM_CHAR','TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII CREST','SUBS_DIGITS_TRANSFORM_CHAR','TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Comp Sensitive','SUBS_DIGITS_TRANSFORM_CHAR','TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Sync','INHERIT_HO','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Obscure','SUBS_DIGITS_TRANSFORM_CHAR','TDC',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Email','OBFUS_EMAIL','OFE',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Holder Date','DATE30_DAYS','RD30',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Cheque Number','CHEQUE_SHUFFLE','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Country Partition','COUNTRY_PARTITION','EXCLUDE',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Sort Code Key','GEN_SORT_KEY','EXCLUDE',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Configuration','NONE','EXCLUDE',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Obscure Text','OBSFUS_TEXT','RN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Designation','DESIGNATION','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Bank Account','OBFUS_BANK_ACCOUNT','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Bank Address','SHUFFLE_BANK_ADDRESS','MAN',null);
Insert into PC_OBFUSCATN_RULES (STEREO_TYPE,TECHNIQUE,TRANS_FUNCTION,EXECUTION_PRIOR) values ('PII Bank Account Sync','INHERIT_BA','MAN',null);

commit;
