set verify on

--------------------------------------------------------
PROMPT Creating Table PAYMENTS_TMP1
--------------------------------------------------------
  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..PAYMENTS_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /
  
  CREATE TABLE &&ANON_OWNER..PAYMENTS_TMP1 
   (	PAYMENT_ID NUMBER(*,0), 
--	CURRENCY_CODE VARCHAR2(3 CHAR), 
--	CASH_ACC_GRPS_ID NUMBER(*,0), 
--	CASH_TRANSACTION_ID NUMBER(*,0), 
--	COUNTRY_CODE VARCHAR2(2 CHAR), 
--	MANDATE_TYPE_ID NUMBER(*,0), 
--	CTYPE_CODE VARCHAR2(10 CHAR), 
--	REISSUE_FOR_PAYMENT_ID NUMBER(*,0), 
--	REISSUE_BY_PAYMENT_ID NUMBER(*,0), 
	CHEQUE_NO NUMBER(6,0), 
	COMMENT_TEXT VARCHAR2(4000 CHAR), 
	PAYMENT_REFERENCE VARCHAR2(18 CHAR), 
--	PAYMENT_STATUS_REF VARCHAR2(10 CHAR), 
--	STATUS_CHANGE_DATE DATE, 
	DISPATCH_ADDRESS_LINE1 VARCHAR2(35 CHAR), 
	DISPATCH_ADDRESS_LINE2 VARCHAR2(35 CHAR), 
	DISPATCH_ADDRESS_LINE3 VARCHAR2(35 CHAR), 
	DISPATCH_ADDRESS_LINE4 VARCHAR2(35 CHAR), 
	DISPATCH_ADDRESS_LINE5 VARCHAR2(35 CHAR), 
	DISPATCH_ADDRESS_LINE6 VARCHAR2(35 CHAR), 
	POSTCODE_LEFT VARCHAR2(4 CHAR), 
	POSTCODE_RIGHT VARCHAR2(3 CHAR), 
	IRISH_DISTRIBUTION_CODE VARCHAR2(10 CHAR), 
--	HIGH_PRIOROTY_YN VARCHAR2(1 CHAR), 
--	PAYMENT_AMOUNT NUMBER(17,3), 
--	PAYMENT_DATE DATE, 
--	POST_DATE DATE, 
--	EXTRACT_DATE DATE, 
	PAYER_ALIAS VARCHAR2(50 CHAR), 
	PAYER_ACCOUNT_NUMBER VARCHAR2(22 CHAR), 
	PAYER_SORTCODE VARCHAR2(9 CHAR), 
--	CLEARED_DATE DATE, 
--	PAYEE_REF VARCHAR2(50 CHAR), 
	PAYEE_NAME1 VARCHAR2(35 CHAR), 
	PAYEE_NAME2 VARCHAR2(35 CHAR), 
	PAYEE_NAME3 VARCHAR2(35 CHAR), 
	PAYEE_NAME4 VARCHAR2(35 CHAR), 
	PAYEE_NAME5 VARCHAR2(35 CHAR), 
	PAYER_IBAN VARCHAR2(34 CHAR), 
	PAYER_BIC VARCHAR2(29 CHAR), 
	DISPATCH_NAME1 VARCHAR2(35 CHAR), 
	DISPATCH_NAME2 VARCHAR2(35 CHAR), 
--	CONVERSION_DATE DATE, 
--	CONVERSION_RATE NUMBER(17,3), 
--	CONVERTED_AMOUNT NUMBER(17,3), 
--	CURRENCY_CODE1 VARCHAR2(3 CHAR), 
--	FX_REFERENCE VARCHAR2(16 CHAR), 
--	ISDRAFT_YN VARCHAR2(1 CHAR), 
	FX_COMMENTS VARCHAR2(255 CHAR), 
	FX_NOTES VARCHAR2(255 CHAR), 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE, 
--	PAYMENT_METHOD_CODE VARCHAR2(10 CHAR), 
--	PAYMENT_STATUS_TYPE_CODE VARCHAR2(10 CHAR), 
--	PAYMENT_TYPE_CODE VARCHAR2(10 CHAR), 
--	PAYMENT_FILE_NAME VARCHAR2(300 CHAR), 
	PAYEE_ALIAS VARCHAR2(50 CHAR), 
	PAYEE_ACCOUNT_NUMBER VARCHAR2(22 CHAR), 
	PAYEE_BIC VARCHAR2(29 CHAR), 
	PAYEE_IBAN VARCHAR2(34 CHAR), 
	PAYEE_SORTCODE VARCHAR2(9 CHAR), 
--	PAYEE_BRANCH_NAME VARCHAR2(50 CHAR), 
	PAYEE_CHEQUEADDRESS_LINE1 VARCHAR2(35 CHAR), 
	PAYEE_CHEQUEADDRESS_LINE2 VARCHAR2(35 CHAR), 
	PAYEE_CHEQUEADDRESS_LINE3 VARCHAR2(35 CHAR), 
	PAYEE_CHEQUEADDRESS_LINE4 VARCHAR2(35 CHAR), 
	PAYEE_CHEQUEADDRESS_LINE5 VARCHAR2(35 CHAR), 
	PAYEE_CHEQUEADDRESS_LINE6 VARCHAR2(35 CHAR), 
--	PAYEE_CLIENT_OWNED_BANKACC VARCHAR2(1 CHAR), 
	PAYEE_BUILDING_SOC_ROLL_NO VARCHAR2(18 CHAR), 
	PAYEE_INTERNAT_BRANCH_IDENT VARCHAR2(8 CHAR), 
--	PAYEE_BANK_NAME VARCHAR2(50 CHAR), 
--	PAYEE_COUNTRY VARCHAR2(2 CHAR), 
	PAYEE_BUILDING_SOC_ACC_NO VARCHAR2(10 CHAR), 
	PAYEE_INTERNAT_ACCOUNT_NO VARCHAR2(34 CHAR), 
	SWIFT_CODE VARCHAR2(11 CHAR), 
--	CONSOLIDATION_IVC VARCHAR2(11 CHAR), 
--	LASER_CHEQUE_YN VARCHAR2(1 CHAR), 
--	GLOBAL_CREST_TRAN_ID NUMBER(*,0), 
	PAYMENT_PTCP_ID VARCHAR2(5 CHAR), 
--	PRINT_GROUP_CODE VARCHAR2(4 CHAR), 
--	PRINT_LOCATION VARCHAR2(4 CHAR), 
--	PARENT_SORT_CODE VARCHAR2(9 CHAR), 
	PARENT_CHEQUE_NUMBER NUMBER(6,0), 
	PARENT_ACCOUNT_NUMBER VARCHAR2(22 CHAR), 
--	PARENT_IVC_REFERENCE VARCHAR2(8 CHAR), 
--	SIBLING_SORT_CODE VARCHAR2(9 CHAR), 
	SIBLING_CHEQUE_NUMBER NUMBER(6,0), 
	SIBLING_ACCOUNT_NUMBER VARCHAR2(22 CHAR), 
--	SIBLING_IVC_REFERENCE VARCHAR2(8 CHAR), 
--	PAYMENT_LETTER_TYPE_CODE VARCHAR2(10 CHAR), 
--	FX_NOTES_TYPE NUMBER(*,0), 
	FX_SETTLEMENT_ACCOUNT_NUMBER VARCHAR2(34 CHAR), 
--	FX_SETTLEMENT_SORT_CODE VARCHAR2(9 CHAR), 
	FX_CLIENT_REF VARCHAR2(20 CHAR) 
--	CREST_MESSAGE_TYPE_CODE VARCHAR2(10 CHAR), 
--	SOCIETY_ACC_ROLL_NUMBER VARCHAR2(18 CHAR), 
--	REISSUE_DATE DATE
   );
--------------------------------------------------------
PROMPT Creating Constraints for Table PAYMENTS_TMP1
--------------------------------------------------------

--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (MANDATE_TYPE_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (PAYMENT_STATUS_REF NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (STATUS_CHANGE_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (PAYMENT_AMOUNT NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (PAYMENT_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (POST_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (EXTRACT_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (ISDRAFT_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (PAYMENT_METHOD_CODE NOT NULL ENABLE);
--ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (PAYMENT_STATUS_TYPE_CODE NOT NULL ENABLE);
 -- ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (LASER_CHEQUE_YN NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (PAYMENT_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (CASH_ACC_GRPS_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..PAYMENTS_TMP1 MODIFY (CASH_TRANSACTION_ID NOT NULL ENABLE);

--------------------------------------------------------
PROMPT Creating Table PAYMENTS_BASE
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..PAYMENTS_BASE'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /
  
  CREATE TABLE &&ANON_OWNER..PAYMENTS_BASE 
   (           "PAYMENT_ID" NUMBER(38,0) NOT NULL ENABLE, 
                "PAYER_ACCOUNT_NUMBER" VARCHAR2(22 CHAR), 
                "PAYER_SORTCODE" VARCHAR2(9 CHAR), 
                "CHEQUE_NO" NUMBER(6,0), 
                "PARENT_ACCOUNT_NUMBER" VARCHAR2(22 CHAR), 
                "PARENT_SORT_CODE" VARCHAR2(9 CHAR), 
                "PARENT_CHEQUE_NUMBER" NUMBER(6,0), 
                "SIBLING_ACCOUNT_NUMBER" VARCHAR2(22 CHAR), 
                "SIBLING_SORTCODE" VARCHAR2(9 CHAR), 
                "SIBLING_CHEQUE_NUMBER" NUMBER(6,0), 
                "BANK_ACCOUNT_ID" NUMBER(38,0), 
                "PAYEE_NAME1" VARCHAR2(35 CHAR), 
                "PAYEE_NAME2" VARCHAR2(35 CHAR), 
                "PAYEE_NAME3" VARCHAR2(35 CHAR), 
                "PAYEE_NAME4" VARCHAR2(35 CHAR), 
                "PAYEE_NAME5" VARCHAR2(35 CHAR), 
                "ADDRESS_LINE1" VARCHAR2(35 CHAR), 
                "ADDRESS_LINE2" VARCHAR2(35 CHAR), 
                "ADDRESS_LINE3" VARCHAR2(35 CHAR), 
                "ADDRESS_LINE4" VARCHAR2(35 CHAR), 
                "ADDRESS_LINE5" VARCHAR2(35 CHAR), 
                "ADDRESS_LINE6" VARCHAR2(35 CHAR), 
                "POSTCODE_LEFT" VARCHAR2(4 CHAR), 
                "POSTCODE_RIGHT" VARCHAR2(3 CHAR), 
                "IRISH_DISTRIBUTION_CODE" VARCHAR2(10 CHAR), 
                "FX_COMMENTS" VARCHAR2(255 CHAR), 
                "FX_NOTES" VARCHAR2(255 CHAR), 
                "COMMENT_TEXT" VARCHAR2(4000 CHAR), 
                "PAYEE_BUILDING_SOC_ACC_NO" VARCHAR2(18 CHAR), 
                "PAYEE_INTERNAT_ACCOUNT_NO" VARCHAR2(34 CHAR), 
                "PAYEE_BUILDING_SOC_ROLL_NO" VARCHAR2(18 CHAR), 
                "PAYEE_ACCOUNT_NUMBER" VARCHAR2(22 CHAR), 
                "PAYEE_INTERNAT_BRANCH_IDENT" VARCHAR2(8 CHAR), 
                "DISPATCH_NAME1" VARCHAR2(35 CHAR), 
                "DISPATCH_NAME2" VARCHAR2(35 CHAR)
   );
   
--------------------------------------------------------
PROMPT Creating Table CHEQUE_RANGES_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /
  
  CREATE TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 
   (	CHEQUE_RANGE_ID NUMBER(*,0), 
	BANK_ACCOUNT_ID NUMBER(*,0), 
	CHEQUE_RANGE_TYPE_CODE VARCHAR2(10 CHAR), 
	END_NO NUMBER(6,0), 
--	EXHAUSTIVE_ACTION_CONT_YN VARCHAR2(1 CHAR), 
	LAST_CHEQUE_NO_USED NUMBER(6,0), 
	START_NO NUMBER(6,0), 
	WARNING_THRESHOLD NUMBER(6,0)--, 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
   );
   
--------------------------------------------------------
PROMPT Creating Table PAYMENTS_BASE_FIN
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..PAYMENTS_BASE_FIN'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /
  
  CREATE TABLE &&ANON_OWNER..PAYMENTS_BASE_FIN 
   (	PAYMENT_ID NUMBER(*,0), 
	CHEQUE_NO NUMBER(6,0), 
	KEY_NS NUMBER, 
	PAYER_ACCOUNT_NUMBER VARCHAR2(22 CHAR), 
	PAYER_SORTCODE VARCHAR2(9 CHAR), 
	PAYMENT_DATE DATE, 
	BANK_ACCOUNT_ID NUMBER(*,0), 
	CHEQUE_NO_HASH NUMBER, 
	CHEQUE_G_MIN_KEY_NS NUMBER, 
	CHEQUE_G_MAX_KEY_NS NUMBER, 
	RANDOMISE_ORDER NUMBER, 
	NEW_CHEQUE_NO NUMBER(6,0), 
	ADDRESS_LINE1 VARCHAR2(35 CHAR), 
	ADDRESS_LINE2 VARCHAR2(35 CHAR), 
	ADDRESS_LINE3 VARCHAR2(35 CHAR), 
	ADDRESS_LINE4 VARCHAR2(35 CHAR), 
	ADDRESS_LINE5 VARCHAR2(35 CHAR), 
	ADDRESS_LINE6 VARCHAR2(35 CHAR), 
	POSTCODE_LEFT VARCHAR2(4 CHAR), 
	POSTCODE_RIGHT VARCHAR2(3 CHAR), 
	IRISH_DISTRIBUTION_CODE VARCHAR2(10 CHAR), 
	SHUFFLE_CHEQUE_NO NUMBER(6,0), 
	CHEQUE_RANGE_TYPE_CODE VARCHAR2(10 CHAR), 
	FX_COMMENTS_ANON VARCHAR2(255 CHAR), 
	FX_NOTES_ANON VARCHAR2(255 CHAR), 
	PAYMENT_REFERENCE_ANON VARCHAR2(18 CHAR), 
	PAYER_BIC_INHERIT VARCHAR2(29 CHAR), 
	PAYER_IBAN_INHERIT VARCHAR2(34 CHAR), 
	PAYER_SORTCODE_INHERIT VARCHAR2(9 CHAR), 
	SIBLING_ACCOUNT_NUMBER_ANON VARCHAR2(22 CHAR), 
	PAYER_ALIAS_ANON VARCHAR2(50 CHAR), 
	PARENT_CHEQUE_NUMBER_ANON NUMBER(6,0), 
	COMMENT_TEXT_ANON VARCHAR2(4000 CHAR), 
	PAYEE_BANK_NAME VARCHAR2(50 CHAR), 
	PAYEE_BRANCH_NAME VARCHAR2(50 CHAR), 
	PAYEE_BUILDING_SOC_ACC_NO VARCHAR2(18 CHAR), 
	PAYEE_INTERNAT_ACCOUNT_NO VARCHAR2(34 CHAR), 
	PAYEE_BUILDING_SOC_ROLL_NO VARCHAR2(18 CHAR), 
	DISPATCH_NAME1 VARCHAR2(35 CHAR), 
	DISPATCH_NAME2 VARCHAR2(35 CHAR), 
	PAYEE_NAME1 VARCHAR2(35 CHAR), 
	PAYEE_NAME2 VARCHAR2(35 CHAR), 
	PAYEE_NAME3 VARCHAR2(35 CHAR), 
	PAYEE_NAME4 VARCHAR2(35 CHAR), 
	PAYEE_NAME5 VARCHAR2(35 CHAR), 
	PARENT_ACCOUNT_NUMBER_ANON VARCHAR2(22 CHAR)
   );
   
--------------------------------------------------------
PROMPT Creating Index PBF_INDX1
--------------------------------------------------------

  CREATE INDEX PBF_INDX1 ON &&ANON_OWNER..PAYMENTS_BASE_FIN (PAYMENT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index PBF_INDX2
--------------------------------------------------------

  CREATE INDEX PBF_INDX2 ON &&ANON_OWNER..PAYMENTS_BASE_FIN (BANK_ACCOUNT_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index PAYMENTS_B4
--------------------------------------------------------

  CREATE INDEX PAYMENTS_B4 ON &&ANON_OWNER..PAYMENTS_BASE_FIN (KEY_NS) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;

--------------------------------------------------------
PROMPT Creating Constraints for Table CHEQUE_RANGES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (CHEQUE_RANGE_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (BANK_ACCOUNT_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (CHEQUE_RANGE_TYPE_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (END_NO NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (EXHAUSTIVE_ACTION_CONT_YN NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (LAST_CHEQUE_NO_USED NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (START_NO NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (WARNING_THRESHOLD NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CHEQUE_RANGES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
PROMPT Creating Constraints for Table PAYMENTS_BASE_FIN
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..PAYMENTS_BASE_FIN MODIFY (PAYMENT_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..PAYMENTS_BASE_FIN MODIFY (PAYMENT_DATE NOT NULL ENABLE);

--------------------------------------------------------
PROMPT Creating Table BANK_BRANCHES_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..BANK_BRANCHES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /
  
  CREATE TABLE &&ANON_OWNER..BANK_BRANCHES_TMP1 
   (	BANK_SORT_CODE VARCHAR2(6 CHAR), 
	FINANCE_ORG_ID NUMBER(*,0), 
	BRANCH_NAME VARCHAR2(50 CHAR), 
	CLOSURE_DATE DATE, 
	STATUS VARCHAR2(6 CHAR), 
	ADDRESS_LINE1 VARCHAR2(35 CHAR), 
	ADDRESS_LINE2 VARCHAR2(35 CHAR), 
	ADDRESS_LINE3 VARCHAR2(35 CHAR), 
	ADDRESS_LINE4 VARCHAR2(35 CHAR), 
	ADDRESS_LINE5 VARCHAR2(35 CHAR), 
	ADDRESS_LINE6 VARCHAR2(35 CHAR), 
	POSTCODE_LEFT VARCHAR2(4 CHAR), 
	POSTCODE_RIGHT VARCHAR2(3 CHAR), 
	COUNTRY_CODE VARCHAR2(2 CHAR), 
	CREATED_BY VARCHAR2(64 CHAR), 
	CREATED_DATE DATE, 
	MODIFIED_BY VARCHAR2(64 CHAR), 
	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
   );
  
  
--------------------------------------------------------
PROMPT Creating Table HOLDER_MANDATES_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1 
   (	HOLDER_MANDATE_ID NUMBER(*,0), 
	COMP_CODE VARCHAR2(4 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
	CLASS_CODE VARCHAR2(2 CHAR), 
	MANDATE_TYPE_ID NUMBER(*,0), 
--	BANK_SORT_CODE VARCHAR2(6 CHAR), 
	BUILDING_SOCIETY_BRANCH_ID NUMBER(*,0), 
--	CURRENCY_CODE VARCHAR2(3 CHAR), 
--	BANK_ACCOUNT_NUMBER VARCHAR2(10 CHAR), 
--	SOCIETY_ACC_ROLL_NUMBER VARCHAR2(18 CHAR), 
--	ACCOUNT_REFERENCE VARCHAR2(50 CHAR), 
--	DRAFT_MANDATE_REF VARCHAR2(25 CHAR), 
--	BIC_CODE VARCHAR2(29 CHAR), 
	PAYEE_NAME VARCHAR2(150 CHAR), 
--	IBAN_NUMBER VARCHAR2(34 CHAR), 
--	BANK_NAME VARCHAR2(35 CHAR), 
--	INTERNATIONAL_ACCOUNT_NUM VARCHAR2(34 CHAR), 
	ADDRESS_LINE1 VARCHAR2(35 CHAR), 
	ADDRESS_LINE2 VARCHAR2(35 CHAR), 
	ADDRESS_LINE3 VARCHAR2(35 CHAR), 
	ADDRESS_LINE4 VARCHAR2(35 CHAR), 
	ADDRESS_LINE5 VARCHAR2(35 CHAR), 
	ADDRESS_LINE6 VARCHAR2(35 CHAR), 
	POSTCODE_LEFT VARCHAR2(4 CHAR), 
	POSTCODE_RIGHT VARCHAR2(3 CHAR), 
	IRISH_DISTRIBUTION_CODE VARCHAR2(10 CHAR)--, 
--	COUNTRY_CODE VARCHAR2(2 CHAR), 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE, 
--	POSTING_PRISM_TASK_ID NUMBER(*,0), 
--	POSTING_DATE DATE, 
--	POSTING_BATCH_ID NUMBER(6,0), 
--	POSTING_TRANSACTION_ID NUMBER(*,0)
   );
--------------------------------------------------------
PROMPT Creating Constraints for Table BANK_BRANCHES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..BANK_BRANCHES_TMP1 MODIFY (BANK_SORT_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..BANK_BRANCHES_TMP1 MODIFY (FINANCE_ORG_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..BANK_BRANCHES_TMP1 MODIFY (STATUS NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_BRANCHES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_BRANCHES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_BRANCHES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_BRANCHES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
PROMPT Creating Constraints for Table HOLDER_MANDATES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1 MODIFY (HOLDER_MANDATE_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1 MODIFY (COMP_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1 MODIFY (IVC_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1 MODIFY (MANDATE_TYPE_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_MANDATES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);


--------------------------------------------------------
PROMPT Creating Table BANK_BRANCHES_TMP2
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..BANK_BRANCHES_TMP2'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..BANK_BRANCHES_TMP2 
   (	BANK_SORT_CODE VARCHAR2(6 CHAR), 
	FINANCE_ORG_ID NUMBER(*,0), 
	KEY_NS NUMBER, 
	ADDRESS_LINE1 VARCHAR2(35 CHAR), 
	ADDRESS_LINE2 VARCHAR2(35 CHAR), 
	ADDRESS_LINE3 VARCHAR2(35 CHAR), 
	ADDRESS_LINE4 VARCHAR2(35 CHAR), 
	ADDRESS_LINE5 VARCHAR2(35 CHAR), 
	ADDRESS_LINE6 VARCHAR2(35 CHAR), 
	POSTCODE_LEFT VARCHAR2(4 CHAR), 
	POSTCODE_RIGHT VARCHAR2(3 CHAR), 
	ADDR_KEY VARCHAR2(217 BYTE)
   );
   
--------------------------------------------------------
PROMPT Creating Table HOLDER_LABELS_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..HOLDER_LABELS_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..HOLDER_LABELS_TMP1 
   (	HOLDER_LABEL_ID NUMBER, 
	HOLDER_TYPE_CODE VARCHAR2(1 CHAR), 
	HOLDER_LABEL_TYPE_CODE VARCHAR2(10 CHAR), 
	COMP_CODE VARCHAR2(4 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
	LABEL_LINE_1 VARCHAR2(4000 CHAR), 
	LABEL_LINE_2 VARCHAR2(4000 CHAR), 
	LABEL_LINE_3 VARCHAR2(4000 CHAR), 
	LABEL_LINE_4 VARCHAR2(4000 CHAR)
   );
   
--------------------------------------------------------
PROMPT Creating Table HOLDER_EMPLOYEE_DETAILS_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..HOLDER_EMPLOYEE_DETAILS_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..HOLDER_EMPLOYEE_DETAILS_TMP1 
   (	HOLDER_EMPLOYEE_DETAIL_ID NUMBER(*,0), 
	COMP_CODE VARCHAR2(4 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
--	COMP_LOCATION_ID NUMBER(*,0), 
--	DIVISION_ID NUMBER(*,0), 
--	TAX_DETAIL_ID NUMBER(*,0), 
--	PAYROLL_ID NUMBER(*,0), 
	GENDER VARCHAR2(1 CHAR), 
	DATE_OF_BIRTH DATE, 
	NATIONAL_INSURANCE_NO VARCHAR2(25 CHAR), 
	PERSONNEL_NUMBER VARCHAR2(25 CHAR), 
	PAYROLL_NUMBER VARCHAR2(25 CHAR)--, 
--	EMPLOYMENT_START_DATE_NT DATE, 
--	EMPLOYER_COMP_EFFECT_DATE_NT DATE, 
--	EMPLOYER_DIV_EFFECT_DATE_NT DATE, 
--	EMPLOYER_LOC_EFFECT_DATE_NT DATE, 
--	PAYROLL_NAME_EFFECT_DATE_NT DATE, 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
   );
   
--------------------------------------------------------
PROMPT Creating Table HOLDER_LABELS_TMP2
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..HOLDER_LABELS_TMP2'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..HOLDER_LABELS_TMP2 
   (	HOLDER_LABEL_ID NUMBER(38,0), 
	HOLDER_TYPE_CODE VARCHAR2(1 CHAR), 
	HOLDER_LABEL_TYPE_CODE VARCHAR2(10 CHAR), 
	COMP_CODE VARCHAR2(4 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
	MAIN_HOLDER VARCHAR2(1163 BYTE), 
	JOINT_HOLDERS VARCHAR2(4000 CHAR), 
	COMPANIES VARCHAR2(164 CHAR), 
	JOINT_COMPANIES VARCHAR2(4000 CHAR), 
	TRUSTEES VARCHAR2(266 CHAR), 
	JOINT_TRUSTEES VARCHAR2(4000 CHAR)
   );
   
--------------------------------------------------------
PROMPT Creating Table HOLDER_LABELS_TMP3
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..HOLDER_LABELS_TMP3'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..HOLDER_LABELS_TMP3 
   (	HOLDER_TYPE_CODE VARCHAR2(1 CHAR), 
	OTHER_TITLE VARCHAR2(20 CHAR), 
	HOLDER_LABEL_ID NUMBER(38,0), 
	HOLDER_LABEL_TYPE_CODE VARCHAR2(10 CHAR), 
	COMP_CODE VARCHAR2(4 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
	FORENAME VARCHAR2(70 CHAR), 
	SURNAME VARCHAR2(50 CHAR), 
	TITLE VARCHAR2(50 CHAR), 
	INITIALS VARCHAR2(70 CHAR), 
	FIRST_FORENAME VARCHAR2(70 CHAR), 
	TAIL_INITS VARCHAR2(70 CHAR), 
	SUFFIX VARCHAR2(20 CHAR), 
	COMPANY_NAME VARCHAR2(150 CHAR), 
	TRUSTEE_NAME VARCHAR2(50 CHAR), 
	TRUST_NAME VARCHAR2(100 CHAR), 
	TRUST_NAME_INITIALS VARCHAR2(100 CHAR), 
	TRUST_NAME_FIRST_NAME VARCHAR2(100 CHAR), 
	TRUST_NAME_TAIL_INITS VARCHAR2(100 CHAR), 
	JH_SURNAMES VARCHAR2(4000 CHAR), 
	JH_COMPANY_NAMES VARCHAR2(4000 CHAR), 
	JH_TRUSTEE_NAMES VARCHAR2(4000 CHAR), 
	JH_FORENAMES_SURNAMES VARCHAR2(4000 CHAR), 
	JH_INIT_SURNAMES VARCHAR2(4000 CHAR), 
	JH_FIRST_FORENAME_TAIL_INIT VARCHAR2(4000 CHAR), 
	DESIGNATION_NAME VARCHAR2(8 CHAR)
   );
   
--------------------------------------------------------
PROMPT Creating Table HOLDER_ADDRESSES_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /
  
  CREATE TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 
   (	HOLDER_ADDRESS_ID NUMBER(*,0), 
	COMP_CODE VARCHAR2(4 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
	ADDRESS_TYPE_ID NUMBER(*,0), 
--	CORRESPONDENCE_YN VARCHAR2(1 CHAR), 
	ADDRESS_LINE1 VARCHAR2(35 CHAR), 
	ADDRESS_LINE2 VARCHAR2(35 CHAR), 
	ADDRESS_LINE3 VARCHAR2(35 CHAR), 
	ADDRESS_LINE4 VARCHAR2(35 CHAR), 
	ADDRESS_LINE5 VARCHAR2(35 CHAR), 
	ADDRESS_LINE6 VARCHAR2(35 CHAR), 
	POSTCODE_LEFT VARCHAR2(4 CHAR), 
	POSTCODE_RIGHT VARCHAR2(3 CHAR), 
	COUNTRY_CODE VARCHAR2(2 CHAR), 
	IRISH_DISTRIBUTION_CODE VARCHAR2(10 CHAR)--, 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE, 
--	POSTING_PRISM_TASK_ID NUMBER(*,0), 
--	POSTING_DATE DATE, 
--	POSTING_BATCH_ID NUMBER(6,0), 
--	POSTING_TRANSACTION_ID NUMBER(*,0)
   );
   
--------------------------------------------------------
PROMPT Creating Index BB_IDX1
--------------------------------------------------------

  CREATE INDEX BB_IDX1 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (NVL(ADDRESS_LINE1,'%')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index BB_IDX2
--------------------------------------------------------

  CREATE INDEX BB_IDX2 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (NVL(ADDRESS_LINE2,'%')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index BB_IDX3
--------------------------------------------------------

  CREATE INDEX BB_IDX3 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (NVL(ADDRESS_LINE3,'%')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index BB_IDX4
--------------------------------------------------------

  CREATE INDEX BB_IDX4 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (NVL(ADDRESS_LINE4,'%')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index BB_IDX5
--------------------------------------------------------

  CREATE INDEX BB_IDX5 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (NVL(ADDRESS_LINE5,'%')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index BB_IDX6
--------------------------------------------------------

  CREATE INDEX BB_IDX6 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (NVL(ADDRESS_LINE6,'%')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index BB_IDX7
--------------------------------------------------------

  CREATE INDEX BB_IDX7 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (NVL(POSTCODE_LEFT,'%')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index BB_IDX8
--------------------------------------------------------

  CREATE INDEX BB_IDX8 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (NVL(POSTCODE_RIGHT,'%')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index BB_IDX20
--------------------------------------------------------

  CREATE INDEX BB_IDX20 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (NVL(ADDR_KEY,'%')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index BB_IDX19
--------------------------------------------------------

  CREATE INDEX BB_IDX19 ON &&ANON_OWNER..BANK_BRANCHES_TMP2 (ADDR_KEY) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Index HOLDER_LABELS_TMP1_IDX
--------------------------------------------------------

  CREATE INDEX HOLDER_LABELS_TMP1_IDX ON &&ANON_OWNER..HOLDER_LABELS_TMP1 (HOLDER_LABEL_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;
--------------------------------------------------------
PROMPT Creating Constraints for Table BANK_BRANCHES_TMP2
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..BANK_BRANCHES_TMP2 MODIFY (BANK_SORT_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..BANK_BRANCHES_TMP2 MODIFY (FINANCE_ORG_ID NOT NULL ENABLE);
--------------------------------------------------------
PROMPT Creating Constraints for Table HOLDER_EMPLOYEE_DETAILS_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..HOLDER_EMPLOYEE_DETAILS_TMP1 MODIFY (HOLDER_EMPLOYEE_DETAIL_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_EMPLOYEE_DETAILS_TMP1 MODIFY (COMP_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_EMPLOYEE_DETAILS_TMP1 MODIFY (IVC_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_EMPLOYEE_DETAILS_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_EMPLOYEE_DETAILS_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_EMPLOYEE_DETAILS_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_EMPLOYEE_DETAILS_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
PROMPT Creating Constraints for Table HOLDER_ADDRESSES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (HOLDER_ADDRESS_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (COMP_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (IVC_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (ADDRESS_TYPE_ID NOT NULL ENABLE);
 -- ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (CORRESPONDENCE_YN NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (ADDRESS_LINE1 NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_ADDRESSES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);

--------------------------------------------------------
PROMPT Creating Table BANK_ACCOUNTS_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 
   (	BANK_ACCOUNT_ID NUMBER(*,0), 
--	CURRENCY_CODE VARCHAR2(3 CHAR), 
--	BANK_ACCOUNT_TYPE_CODE VARCHAR2(10 CHAR), 
--	REG_STATUS_TYPE_CODE VARCHAR2(10 CHAR), 
--	STATUS_TYPE_CODE VARCHAR2(10 CHAR), 
--	COUNTRY_CODE VARCHAR2(2 CHAR), 
--	SECOND_SORTCODE VARCHAR2(9 CHAR), 
--	ALIAS_NAME VARCHAR2(50 CHAR), 
--	BACS_CODE VARCHAR2(6 CHAR), 
--	BLOCKPAYMENT_YN VARCHAR2(1 CHAR), 
	CAPITA_REFERENCE VARCHAR2(20 CHAR), 
--	COMMENT_TEXT VARCHAR2(4000 CHAR), 
--	ISVIRTUAL_YN VARCHAR2(1 CHAR), 
--	STATUS_CHANGE_DATE DATE, 
--	CLIENT_OWNED_BANK_ACCOUNT_YN VARCHAR2(1 CHAR), 
	ACCOUNT_NO VARCHAR2(22 CHAR), 
	ACCOUNT_NO_ANON VARCHAR2(22 CHAR),  
	ACCOUNT_NAME VARCHAR2(108 CHAR), 
--	BANK_NAME VARCHAR2(50 CHAR), 
	SORTCODE VARCHAR2(9 CHAR), 
--	INTERNATIONAL_BRANCH_ID VARCHAR2(8 CHAR), 
--	INTERNATIONAL_ACCOUNT_NO VARCHAR2(34 CHAR), 
	IBAN VARCHAR2(34 CHAR), 
--	FAX_NUMBER VARCHAR2(50 CHAR), 
--	BUILDING_SOCIETY_ACCOUNT_NO VARCHAR2(10 CHAR), 
--	BRANCH_NAME VARCHAR2(50 CHAR), 
	BIC VARCHAR2(29 CHAR), 
--	CHEQUEADDRESS_LINE1_TEXT VARCHAR2(35 CHAR), 
--	CHEQUEADDRESS_LINE2_TEXT VARCHAR2(35 CHAR), 
--	CHEQUEADDRESS_LINE3_TEXT VARCHAR2(35 CHAR), 
--	CHEQUEADDRESS_LINE4_TEXT VARCHAR2(35 CHAR), 
--	CHEQUEADDRESS_LINE5_TEXT VARCHAR2(35 CHAR), 
--	CHEQUEADDRESS_LINE6_TEXT VARCHAR2(35 CHAR), 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE, 
--	BANK_PAYMENT_CAT_TYPE_CODE VARCHAR2(10 CHAR), 
--	SWIFT_CODE VARCHAR2(11 CHAR)
    KEY_NS  NUMBER(9,0)
   );
   
--------------------------------------------------------
PROMPT Creating Table HOLDERS_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..HOLDERS_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..HOLDERS_TMP1 
   (	COMP_CODE VARCHAR2(4 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
--	AMALGAMATED_IVC VARCHAR2(11 CHAR), 
--	LAST_CHANGED_DATE DATE, 
--	DELETED_YN VARCHAR2(1 CHAR), 
--	MEMBER_TYPE_EMPLOYEE_YN VARCHAR2(1 CHAR), 
--	MEMBER_TYPE_REGISTRATION_YN VARCHAR2(1 CHAR), 
	SORT_KEY VARCHAR2(34 CHAR), 
--	PARTICIPANT_CODE VARCHAR2(16 CHAR), 
	SHARE_MASTER_HOLDER_CODE VARCHAR2(8 CHAR), 
	REFERENCE_IVC_CODE VARCHAR2(11 CHAR), 
	DESIGNATION_NAME VARCHAR2(8 CHAR), 
--	SHARE_OWNER_START_DATE_NT DATE, 
--	SHARE_OWNER_END_DATE_NT DATE, 
--	COUNTRY_CODE VARCHAR2(2 CHAR), 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE, 
--	NUMBER_OF_HOLDERS_COUNT NUMBER(*,0), 
--	PLEDGE_YN VARCHAR2(1 CHAR), 
--	COURT_PROTECTION_YN VARCHAR2(1 CHAR), 
--	UNCERTIFICATED_YN VARCHAR2(1 CHAR), 
--	AMALGAMATED_YN VARCHAR2(1 CHAR), 
--	CLOSED_YN VARCHAR2(1 CHAR), 
--	CONTROL_YN VARCHAR2(1 CHAR), 
--	CREST_YN VARCHAR2(1 CHAR), 
--	ALERT_YN VARCHAR2(1 CHAR), 
--	COURT_ORDER_YN VARCHAR2(1 CHAR), 
--	POSTING_PRISM_TASK_ID NUMBER(*,0), 
--	POSTING_DATE DATE, 
--	POSTING_BATCH_ID NUMBER(6,0), 
--	POSTING_TRANSACTION_ID NUMBER(*,0), 
--	CONTRIBUTION_PERIOD_TYPE_ID NUMBER(*,0), 
--	EXPAT_YN VARCHAR2(1 CHAR), 
	PREVIOUS_SORTKEY VARCHAR2(34 CHAR), 
--	DISCRETION_RESIDENCY_CODE VARCHAR2(10 CHAR), 
--	INCOME_TAX_RATE_ID NUMBER(*,0), 
--	EMPLOYER_NI_TAX_RATE_ID NUMBER(*,0), 
--	EMPLOYEE_NI_TAX_RATE_ID NUMBER(*,0), 
--	DISCRET_ELECTION_TYPE_CODE VARCHAR2(10 CHAR), 
--	STRIPPED_YN VARCHAR2(1 CHAR), 
	DATE_OF_DEATH DATE
   );
  
--------------------------------------------------------
PROMPT Creating Table SK_TEMP
--------------------------------------------------------  
  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..SK_TEMP'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..SK_TEMP 
   ( COMP_CODE  VARCHAR2(4 BYTE), 
	   HOLDER_SEQ NUMBER, 
	   IVC_CODE   VARCHAR2(11 BYTE), 
	   SK_GEN     VARCHAR2(4000 BYTE)
   );

--------------------------------------------------------
PROMPT Creating Table HOLDER_BASE
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..HOLDER_BASE'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..HOLDER_BASE 
   (	KEY_NS NUMBER, 
	COMP_CODE VARCHAR2(4 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
	--AMALGAMATED_IVC VARCHAR2(11 CHAR), 
	SORT_KEY VARCHAR2(34 CHAR), 
	SORT_KEY_ANON VARCHAR2(34 CHAR), 
--	PARTICIPANT_CODE VARCHAR2(16 CHAR), 
--	PARTICIPANT_CODE_ANON VARCHAR2(16 CHAR), 
	SHARE_MASTER_HOLDER_CODE VARCHAR2(8 CHAR), 
	SHARE_MASTER_HOLDER_CODE_ANON VARCHAR2(8 CHAR), 
	REFERENCE_IVC_CODE VARCHAR2(11 CHAR), 
	REFERENCE_IVC_CODE_ANON VARCHAR2(11 CHAR), 
	DESIGNATION_NAME VARCHAR2(8 CHAR), 
	DESIGNATION_NAME_ANON VARCHAR2(8 CHAR), 
	COUNTRY_CODE VARCHAR2(2 CHAR), 
	COUNTRY_CODE_ANON VARCHAR2(2 CHAR), 
	DATE_OF_DEATH DATE, 
	DATE_OF_DEATH_ANON DATE, 
	GENDER VARCHAR2(1 CHAR), 
	GENDER_ANON VARCHAR2(1 CHAR), 
	DATE_OF_BIRTH DATE, 
	DATE_OF_BIRTH_ANON DATE, 
	NATIONAL_INSURANCE_NO VARCHAR2(25 CHAR), 
	NATIONAL_INSURANCE_NO_ANON VARCHAR2(25 CHAR), 
	PERSONNEL_NUMBER VARCHAR2(25 CHAR), 
	PERSONNEL_NUMBER_ANON VARCHAR2(25 CHAR), 
	PAYROLL_NUMBER VARCHAR2(25 CHAR), 
	PAYROLL_NUMBER_ANON VARCHAR2(25 CHAR), 
	NI_KEY NUMBER
   );

--------------------------------------------------------
PROMPT Creating Index HOLDER_BAS1
--------------------------------------------------------

  CREATE INDEX HOLDER_BAS1 ON &&ANON_OWNER..HOLDER_BASE (KEY_NS) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE PRISM_INDEX;

--------------------------------------------------------
PROMPT Creating Constraints for Table BANK_ACCOUNTS_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (BANK_ACCOUNT_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (CURRENCY_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (BANK_ACCOUNT_TYPE_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (REG_STATUS_TYPE_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (STATUS_TYPE_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (COUNTRY_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (BLOCKPAYMENT_YN NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (CAPITA_REFERENCE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (ISVIRTUAL_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (STATUS_CHANGE_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (CLIENT_OWNED_BANK_ACCOUNT_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..BANK_ACCOUNTS_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
PROMPT Creating Constraints for Table HOLDERS_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..HOLDERS_TMP1 MODIFY (COMP_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDERS_TMP1 MODIFY (IVC_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDERS_TMP1 MODIFY (DELETED_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDERS_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDERS_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDERS_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDERS_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDERS_TMP1 MODIFY (STRIPPED_YN NOT NULL ENABLE);
--------------------------------------------------------
PROMPT Creating Constraints for Table HOLDER_BASE
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..HOLDER_BASE MODIFY (COMP_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_BASE MODIFY (IVC_CODE NOT NULL ENABLE);

--------------------------------------------------------
PROMPT Creating Table DISC_EXER_SPOUSE_DTLS_TMP1
--------------------------------------------------------
  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /
  
  CREATE TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1 
   (	DISCRET_EXERCISE_REQ_ID NUMBER(*,0), 
	SURNAME VARCHAR2(150 CHAR), 
	FORENAMES VARCHAR2(150 CHAR), 
	TITLE VARCHAR2(50 CHAR), 
	ADDRESS_LINE_1 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_2 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_3 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_4 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_5 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_6 VARCHAR2(35 CHAR), 
	POST_CODE_LEFT VARCHAR2(4 CHAR), 
	POST_CODE_RIGHT VARCHAR2(3 CHAR), 
	COUNTRY_CODE VARCHAR2(10 CHAR)
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
   );
   
--------------------------------------------------------
PROMPT Creating Table CASH_IVC_CLASS_COPIES_TMP1
--------------------------------------------------------
  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /
  
  CREATE TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 
   (	CASH_IVC_CLASS_COPY_ID NUMBER(*,0), 
--	IVC_CLASS_COPY_ID NUMBER(*,0), 
--	RESIDUAL_CURRENCY_CODE VARCHAR2(3 CHAR), 
--	CURRENCY_CODE VARCHAR2(3 CHAR), 
--	PAYMENT_METHOD_CODE VARCHAR2(10 CHAR), 
--	COMP_CODE VARCHAR2(4 CHAR), 
--	CLASS_CODE VARCHAR2(2 CHAR), 
--	EVENT_CODE VARCHAR2(20 CHAR), 
--	REINVESTMENT_ID NUMBER(*,0), 
--	RIGHTS_TYPE_CODE VARCHAR2(10 CHAR), 
--	HOLDING NUMBER(22,6), 
--	RESIDUAL_REPAY_AMT NUMBER(17,3), 
--	CASH_ACC_ID NUMBER(*,0), 
--	CASH_ACC_GRP_ID NUMBER(*,0), 
	PAYEE_NAME VARCHAR2(150 CHAR), 
--	INVALID_YN VARCHAR2(1 CHAR), 
--	RETAINED_RESIDUAL_AMT NUMBER(17,3), 
--	NOTE VARCHAR2(4000 CHAR), 
--	CHARITY_RESIDUAL_AMT NUMBER(17,3), 
--	COMPANY_RESIDUAL_AMT NUMBER(17,3), 
--	WITHHOLD_PAY_YN VARCHAR2(1 CHAR), 
--	CONSOLIDATION_NO NUMBER(*,0), 
--	CASH_CALC_COMPLETE_YN VARCHAR2(1 CHAR), 
--	BANK_NAME VARCHAR2(50 CHAR), 
--	SORT_CODE VARCHAR2(9 CHAR), 
--	COUNTRY VARCHAR2(2 CHAR), 
--	ACCOUNT_NO VARCHAR2(22 CHAR), 
--	BUILDING_SOCIETY_ACC_NO VARCHAR2(10 CHAR), 
--	BIC VARCHAR2(29 CHAR), 
--	INTERNATIONAL_ACC_NO VARCHAR2(34 CHAR), 
--	BRANCH_NAME VARCHAR2(50 CHAR), 
--	INTERNATIONAL_BRANCH_ID VARCHAR2(8 CHAR), 
--	IBAN VARCHAR2(34 CHAR), 
--	SOCIETY_ACC_ROLL_NO VARCHAR2(18 CHAR), 
	ADDRESS_LINE_1 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_2 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_3 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_4 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_5 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_6 VARCHAR2(35 CHAR), 
	POST_CODE_LEFT VARCHAR2(4 CHAR), 
	POST_CODE_RIGHT VARCHAR2(3 CHAR), 
	IRISH_DISTRIBUTION_CODE VARCHAR2(10 CHAR)--, 
--	COUNTRY_CODE VARCHAR2(10 CHAR), 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE, 
--	MANDATE_TYPE_ID NUMBER(*,0), 
--	BRANCH_ADDRESS VARCHAR2(250 CHAR), 
--	THLD_INELIGIBLE_YN VARCHAR2(1 CHAR), 
--	IPS_CURRENCY_CODE VARCHAR2(3 CHAR), 
--	CFWD_REIN_FRACT_RULE_TYPE_CODE VARCHAR2(10 CHAR), 
--	BFWD_RESIDUAL_AMT NUMBER(17,3), 
--	CFWD_RESIDUAL_AMT NUMBER(17,3), 
--	REINVEST_IVC_CLASS_COPY_ID NUMBER(*,0), 
--	CASH_IVC_CLS_COPY_TYPE_CODE VARCHAR2(10 CHAR), 
--	REVOKED_RESIDUAL_TYPE_CODE VARCHAR2(10 CHAR), 
--	REINVESTMENT_CASH_ACC_GRP_ID NUMBER(*,0), 
--	REINVESTMENT_CASH_ACC_ID NUMBER(*,0)
   );
   
--------------------------------------------------------
PROMPT Creating Table MIFID_ENTITIES_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 
   (	MIFID_ENTITY_ID NUMBER, 
--	DERIVED_NAT_COUNTRY_CODE VARCHAR2(2 CHAR), 
--	CONFIRMATION_TYPE_CODE VARCHAR2(10 CHAR), 
--	MIFID_ENTITY_CAT_TYPE_CODE VARCHAR2(10 CHAR), 
--	MIFID_IDENTIFIER_TYPE_ID NUMBER, 
--	MIFID_IDENTIFIER_TYPE_VALUE VARCHAR2(35 CHAR), 
--	NATURAL_PERSON_YN VARCHAR2(1 CHAR), 
--	MIFID_ENTITY_TYPE_CODE VARCHAR2(1 CHAR), 
--	COMP_CODE VARCHAR2(4 CHAR), 
--	ENTITY_SEQUENCE NUMBER, 
	FORENAMES VARCHAR2(140 CHAR), 
	SURNAME VARCHAR2(140 CHAR), 
--	DATE_OF_BIRTH DATE, 
	REGISTER_FORENAMES VARCHAR2(140 CHAR), 
	REGISTER_SURNAME VARCHAR2(140 CHAR)--, 
--	NAME VARCHAR2(140 CHAR), 
--	ACK_1ST_PRTY_NOT_ISSUED_YN VARCHAR2(1 CHAR), 
--	ACK_2ND_PRTY_NOT_ISSUED_YN VARCHAR2(1 CHAR), 
--	DELETION_DATE_NT DATE, 
--	LAST_CONFIRMED_DATE DATE, 
--	LAST_CONFIRMED_BY VARCHAR2(64 CHAR), 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
   );
   
--------------------------------------------------------
PROMPT Creating Table MIFID_TRANSACTION_DETAILS_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..MIFID_TRANSACTION_DETAILS_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..MIFID_TRANSACTION_DETAILS_TMP1 
   (	TRANSACTION_DETAIL_ID NUMBER(*,0), 
--	JOB_ID NUMBER(*,0), 
	BULK_TRADE_ID NUMBER(*,0), 
--	EXTRACT_DATE VARCHAR2(10 BYTE), 
--	TRADE_DATE VARCHAR2(10 BYTE), 
--	REFERENCE VARCHAR2(50 BYTE), 
--	TRADE_TIME VARCHAR2(20 BYTE), 
--	TRADE_REASON VARCHAR2(50 BYTE), 
--	BULK_TRADE_REFERENCE VARCHAR2(50 BYTE), 
--	TICKER VARCHAR2(50 BYTE), 
--	COMPANY_NAME VARCHAR2(60 BYTE), 
--	COMPANY_CODE VARCHAR2(4 BYTE), 
--	ISIN VARCHAR2(12 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
	HOLDER_SURNAME VARCHAR2(50 CHAR)
--	TRADE_TYPE VARCHAR2(50 BYTE), 
--	QUANTITY NUMBER(17,8), 
--	CURRENCY_CODE VARCHAR2(50 CHAR), 
--	SHARE_PRICE NUMBER(17,8), 
--	COMMISSION NUMBER(17,8), 
--	CONSIDERATION NUMBER(17,8), 
--	SETTLEMENT_DATE VARCHAR2(10 BYTE), 
--	DEALER_NAME VARCHAR2(50 BYTE), 
--	COUNTERPARTY VARCHAR2(50 BYTE), 
--	BROKER_CODE VARCHAR2(10 CHAR), 
--	EXECUTION_VENUE VARCHAR2(50 BYTE), 
--	COMMENTS VARCHAR2(50 BYTE), 
--	STOCK_RECEIVED VARCHAR2(50 BYTE), 
--	CHECKED_BY VARCHAR2(50 BYTE), 
--	CHECKED_ON VARCHAR2(10 BYTE), 
--	CHECK_STATUS NUMBER(*,0), 
--	DATA_SOURCE_LOCATION VARCHAR2(50 BYTE), 
--	CREATED_BY VARCHAR2(64 BYTE), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 BYTE), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
   );
   
--------------------------------------------------------
PROMPT Creating Constraints for Table DISC_EXER_SPOUSE_DTLS_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1 MODIFY (DISCRET_EXERCISE_REQ_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1 MODIFY (SURNAME NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1 MODIFY (FORENAMES NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1 MODIFY (ADDRESS_LINE_1 NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_SPOUSE_DTLS_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
PROMPT Creating Constraints for Table CASH_IVC_CLASS_COPIES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (CASH_IVC_CLASS_COPY_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (IVC_CLASS_COPY_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (COMP_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (CLASS_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (EVENT_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (HOLDING NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (INVALID_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (WITHHOLD_PAY_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (CASH_CALC_COMPLETE_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..CASH_IVC_CLASS_COPIES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
PROMPT Creating for Table MIFID_ENTITIES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 MODIFY (MIFID_ENTITY_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 MODIFY (MIFID_ENTITY_CAT_TYPE_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 MODIFY (MIFID_IDENTIFIER_TYPE_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 MODIFY (MIFID_IDENTIFIER_TYPE_VALUE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 MODIFY (NATURAL_PERSON_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_ENTITIES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
PROMPT Creating for Table MIFID_TRANSACTION_DETAILS_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..MIFID_TRANSACTION_DETAILS_TMP1 MODIFY (TRANSACTION_DETAIL_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_TRANSACTION_DETAILS_TMP1 MODIFY (JOB_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_TRANSACTION_DETAILS_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_TRANSACTION_DETAILS_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_TRANSACTION_DETAILS_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_TRANSACTION_DETAILS_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);


--------------------------------------------------------
PROMPT Creating Table DISC_EXER_REQ_MANDATES_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  /

  CREATE TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 
   (	DISC_EXER_REQ_MANDATE_ID NUMBER(*,0), 
	DISCRET_EXERCISE_REQ_ID NUMBER(*,0), 
	MANDATE_TYPE_ID NUMBER(*,0), 
--	USE_FOR_SALES_PROCEEDS_YN VARCHAR2(1 CHAR), 
--	USE_FOR_DIV_PAYS_YN VARCHAR2(1 CHAR), 
	BANK_ACC_NO VARCHAR2(10 CHAR), 
	SOCIETY_ACC_ROLL_NO VARCHAR2(18 CHAR), 
	BANK_SORT_CODE VARCHAR2(6 CHAR), 
	BANK_NAME VARCHAR2(35 CHAR), 
	BANK_ID_CODE_BIC VARCHAR2(29 CHAR), 
	INT_BANK_ACC_NO_IBAN VARCHAR2(34 CHAR), 
	INT_ACC_NO VARCHAR2(34 CHAR), 
	ADDRESS_LINE_1 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_2 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_3 VARCHAR2(35 CHAR), 
	ADDRESS_LINE_6 VARCHAR2(35 CHAR), 
	COUNTRY_CODE VARCHAR2(2 CHAR)--, 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
   );
   
--------------------------------------------------------
PROMPT Creating Table HOLDER_NAMES_TMP1
--------------------------------------------------------
 
  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  / 
 
  CREATE TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 
   (	HOLDER_NAME_ID NUMBER(*,0), 
	COMP_CODE VARCHAR2(4 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
	HOLDER_SEQ NUMBER(*,0), 
	HOLDER_TYPE_CODE VARCHAR2(1 CHAR), 
	TITLE_TYPE_CODE VARCHAR2(10 CHAR), 
	SURNAME VARCHAR2(50 CHAR), 
	FORENAME VARCHAR2(70 CHAR), 
	SUFFIX VARCHAR2(20 CHAR), 
	SALUTATION VARCHAR2(75 CHAR), 
	OTHER_TITLE VARCHAR2(20 CHAR), 
	PREFERRED_NAME VARCHAR2(25 CHAR), 
	TRUST_NAME VARCHAR2(100 CHAR), 
	TRUSTEE_NAME VARCHAR2(50 CHAR), 
	COMPANY_NAME VARCHAR2(150 CHAR)--, 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE, 
--	POSTING_PRISM_TASK_ID NUMBER(*,0), 
--	POSTING_DATE DATE, 
--	POSTING_BATCH_ID NUMBER(6,0), 
--	POSTING_TRANSACTION_ID NUMBER(*,0)
   );
   
--------------------------------------------------------
PROMPT Creating Table COMP_PAYEE_MANDATES_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..COMP_PAYEE_MANDATES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  / 

  CREATE TABLE &&ANON_OWNER..COMP_PAYEE_MANDATES_TMP1 
   (	COMP_PAYEE_ID NUMBER(*,0), 
	MANDATE_TYPE_ID NUMBER(*,0), 
--	COUNTRY_CODE VARCHAR2(2 CHAR), 
--	CURRENCY_CODE VARCHAR2(3 CHAR), 
--	BANK_SORT_CODE VARCHAR2(6 CHAR), 
--	BUILDING_SOCIETY_BRANCH_ID NUMBER(*,0), 
--	BANK_ACCOUNT_NUMBER VARCHAR2(10 CHAR), 
--	INTERNATIONAL_ACCOUNT_NUM VARCHAR2(34 CHAR), 
--	ACCOUNT_REFERENCE VARCHAR2(50 CHAR), 
--	SOCIETY_ACC_ROLL_NUMBER VARCHAR2(18 CHAR), 
--	BIC_CODE VARCHAR2(29 CHAR), 
--	IBAN_NUMBER VARCHAR2(34 CHAR), 
--	BANK_NAME VARCHAR2(35 CHAR), 
	ADDRESS_LINE1 VARCHAR2(35 CHAR), 
	ADDRESS_LINE2 VARCHAR2(35 CHAR), 
	ADDRESS_LINE3 VARCHAR2(35 CHAR), 
	ADDRESS_LINE4 VARCHAR2(35 CHAR), 
	ADDRESS_LINE5 VARCHAR2(35 CHAR), 
	ADDRESS_LINE6 VARCHAR2(35 CHAR), 
	POST_CODE_LEFT VARCHAR2(4 CHAR), 
	POST_CODE_RIGHT VARCHAR2(3 CHAR), 
	IRISH_DISTRIBUTION_CODE VARCHAR2(10 CHAR)--, 
--	CREATED_BY VARCHAR2(64 CHAR), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 CHAR), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
   );
   
--------------------------------------------------------
PROMPT Creating Table MIFID_BULK_TRADES_TMP1
--------------------------------------------------------

  BEGIN
    execute immediate 'DROP TABLE &&ANON_OWNER..MIFID_BULK_TRADES_TMP1'; 
  EXCEPTION WHEN OTHERS THEN null; END;
  / 
  
  CREATE TABLE &&ANON_OWNER..MIFID_BULK_TRADES_TMP1 
   (	BULK_TRADE_ID NUMBER(*,0), 
--	JOB_ID NUMBER(*,0), 
--	TRADE_DATE VARCHAR2(10 BYTE), 
--	REFERENCE VARCHAR2(50 BYTE), 
--	TRADE_TIME VARCHAR2(20 BYTE), 
--	TRADE_REASON VARCHAR2(50 BYTE), 
--	BULK_TRADE_REFERENCE VARCHAR2(50 BYTE), 
--	TICKER VARCHAR2(50 BYTE), 
--	COMPANY_NAME VARCHAR2(60 BYTE), 
--	COMPANY_CODE VARCHAR2(4 BYTE), 
--	ISIN VARCHAR2(12 BYTE), 
	IVC_CODE VARCHAR2(11 BYTE), 
	HOLDER_SURNAME VARCHAR2(50 CHAR)
--	TRADE_TYPE VARCHAR2(50 BYTE), 
--	QUANTITY NUMBER(17,8), 
--	CURRENCY_CODE VARCHAR2(3 CHAR), 
--	SHARE_PRICE NUMBER(17,8), 
--	COMMISSION NUMBER(17,8), 
--	SETTLEMENT_DATE VARCHAR2(10 BYTE), 
--	CONSIDERATION NUMBER(17,8), 
--	COUNTERPARTY VARCHAR2(50 BYTE), 
--	BROKER_CODE VARCHAR2(50 BYTE), 
--	EXECUTION_VENUE VARCHAR2(50 BYTE), 
--	DEALER_NAME VARCHAR2(50 BYTE), 
--	COMMENTS VARCHAR2(50 BYTE), 
--	CHECKER_AUTHORITY VARCHAR2(50 BYTE), 
--	CHECKED_BY VARCHAR2(50 BYTE), 
--	CHECKED_ON VARCHAR2(10 BYTE), 
--	CHECK_STATUS NUMBER(*,0), 
--	DATA_SOURCE_LOCATION VARCHAR2(50 BYTE), 
--	CREATED_BY VARCHAR2(64 BYTE), 
--	CREATED_DATE DATE, 
--	MODIFIED_BY VARCHAR2(64 BYTE), 
--	MOD_TIMESTAMP TIMESTAMP (6) WITH LOCAL TIME ZONE
   );
   
--------------------------------------------------------
--  PROMPT Creating Constraints for Table DISC_EXER_REQ_MANDATES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 MODIFY (DISC_EXER_REQ_MANDATE_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 MODIFY (DISCRET_EXERCISE_REQ_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 MODIFY (MANDATE_TYPE_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 MODIFY (USE_FOR_SALES_PROCEEDS_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 MODIFY (USE_FOR_DIV_PAYS_YN NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..DISC_EXER_REQ_MANDATES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
--  PROMPT Creating Constraints for Table HOLDER_NAMES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 MODIFY (HOLDER_NAME_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 MODIFY (COMP_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 MODIFY (IVC_CODE NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 MODIFY (HOLDER_SEQ NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 MODIFY (HOLDER_TYPE_CODE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..HOLDER_NAMES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
--  PROMPT Creating Constraints for Table COMP_PAYEE_MANDATES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..COMP_PAYEE_MANDATES_TMP1 MODIFY (COMP_PAYEE_ID NOT NULL ENABLE);
  ALTER TABLE &&ANON_OWNER..COMP_PAYEE_MANDATES_TMP1 MODIFY (MANDATE_TYPE_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..COMP_PAYEE_MANDATES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..COMP_PAYEE_MANDATES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..COMP_PAYEE_MANDATES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..COMP_PAYEE_MANDATES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);
--------------------------------------------------------
--  PROMPT Creating Constraints for Table MIFID_BULK_TRADES_TMP1
--------------------------------------------------------

  ALTER TABLE &&ANON_OWNER..MIFID_BULK_TRADES_TMP1 MODIFY (BULK_TRADE_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_BULK_TRADES_TMP1 MODIFY (JOB_ID NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_BULK_TRADES_TMP1 MODIFY (CREATED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_BULK_TRADES_TMP1 MODIFY (CREATED_DATE NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_BULK_TRADES_TMP1 MODIFY (MODIFIED_BY NOT NULL ENABLE);
--  ALTER TABLE &&ANON_OWNER..MIFID_BULK_TRADES_TMP1 MODIFY (MOD_TIMESTAMP NOT NULL ENABLE);

--------------------------------------------------------
PROMPT Creating Table RND_DERM_ADRESSS_LU
--------------------------------------------------------

BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_derm_adresss_lu'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_derm_adresss_lu (disc_exer_req_mandate_id number,address_line1_key number,
    address_line2_key  number,address_line3_key  number);

--------------------------------------------------------
PROMPT Creating Table RND_ADESD_NAME_LOOKUP
--------------------------------------------------------

BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_adesd_name_lookup'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_adesd_name_lookup (discret_exercise_req_id number,surname_key number,forename_key number);

--------------------------------------------------------
PROMPT Creating Table RND_ADESD_ADRESSS_LU
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_adesd_adresss_lu'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_adesd_adresss_lu ( discret_exercise_req_id number,address_line1_key number,
                                                  address_line2_key  number,address_line3_key  number,post_code_key number);
                                                  
--------------------------------------------------------
PROMPT Creating Table RND_CPM_ADRESSS_LU
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_cpm_adresss_lu'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_cpm_adresss_lu (comp_payee_id number,address_line1_key number,
    address_line2_key  number,address_line3_key  number,post_code_key number);

--------------------------------------------------------
PROMPT Creating Table RND_ME_NAME_LOOKUP
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_me_name_lookup'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_me_name_lookup (mifid_entity_id number,surname_key number,forename_key number);

--------------------------------------------------------
PROMPT Creating Table RND_MI_NAME_LOOKUP
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_mi_name_lookup'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_mi_name_lookup (transaction_detail_id number,bulk_trade_id number,surname_key number);

--------------------------------------------------------
PROMPT Creating Table RND_DISP_MANDATE_ADRESSS_LU
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_disp_mandate_adresss_lu'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_disp_mandate_adresss_lu (holder_mandate_id number,address_line1_key number,
                                                        address_line2_key  number,address_line3_key  number,post_code_key number);

--------------------------------------------------------
PROMPT Creating Table RND_DISPATCH_NAME_LOOKUP
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_dispatch_name_lookup'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_dispatch_name_lookup (payment_id number,surname_key number,forename_key number);

--------------------------------------------------------
PROMPT Creating Table RND_ADESD_NAME_LOOKUP
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_adesd_name_lookup'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_adesd_name_lookup (discret_exercise_req_id number,surname_key number,forename_key number);

--------------------------------------------------------
PROMPT Creating Table RND_DISP_PAYMENT_ADRESSS_LU
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..rnd_disp_payment_adresss_lu'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

create table &&ANON_OWNER..rnd_disp_payment_adresss_lu (payment_id number,address_line1_key number,
     address_line2_key  number,address_line3_key  number,post_code_key number);

	 --------------------------------------------------------
PROMPT Creating Table TMP_STAT_TYPE
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..TMP_STAT_TYPE'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 
	 
CREATE TABLE &&ANON_OWNER..TMP_STAT_TYPE (       
     not_equals       NUMBER(12,0), 
     equals           NUMBER(12,0), 
     value_to_null    NUMBER(12,0), 
     value_from_null  NUMBER(12,0), 
     avg_sim_dist     NUMBER(8,2), 
     total_recs_src   NUMBER(12,0), 
     total_recs_tgt   NUMBER(12,0), 
     total_nulls_src  NUMBER(12,0),
     total_nulls_tgt  NUMBER(12,0) 
);	 
	 
--------------------------------------------------------
PROMPT Creating Table TMP_TAB_PK
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..TMP_TAB_PK'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

CREATE TABLE &&ANON_OWNER..TMP_TAB_PK 
(	OWNER          VARCHAR2(128 BYTE), 
	TABLE_NAME     VARCHAR2(128 BYTE), 
	PKCOLS         VARCHAR2(4000 BYTE), 
	LEADING_PKCOL  VARCHAR2(100 BYTE), 
	PKJOIN         VARCHAR2(4000 BYTE)
);	 

--------------------------------------------------------
PROMPT Creating Table TMP_PC_TAB_PK
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..TMP_PC_TAB_PK'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

CREATE TABLE &&ANON_OWNER..TMP_PC_TAB_PK 
(	OWNER VARCHAR2(30 BYTE), 
	TABLE_NAME VARCHAR2(30 BYTE), 
	COLUMN_NAME VARCHAR2(30 BYTE), 
	TECHNIQUE VARCHAR2(4000 BYTE), 
	TRANS_FUNCTION VARCHAR2(4000 BYTE), 
	STEREO_TYPE VARCHAR2(4000 BYTE), 
	PKCOLS VARCHAR2(4000 BYTE), 
	LEADING_PKCOL VARCHAR2(100 BYTE), 
	PKJOIN VARCHAR2(4000 BYTE)
   );

--------------------------------------------------------
PROMPT Creating Table UNUSED_COL_TABS_TMP
--------------------------------------------------------
BEGIN
  execute immediate 'DROP TABLE &&ANON_OWNER..UNUSED_COL_TABS_TMP'; 
EXCEPTION WHEN OTHERS THEN null; END;
/ 

CREATE TABLE &&ANON_OWNER..UNUSED_COL_TABS_TMP 
(	OWNER VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	TABLE_NAME VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	UNUSED_COL_COUNT NUMBER, 
	NUM_ROWS NUMBER, 
	BLOCKS NUMBER, 
	EMPTY_BLOCKS NUMBER, 
	PARTITION_NAME VARCHAR2(128 BYTE), 
	SUBPARTITION_NAME VARCHAR2(128 BYTE)
   );   